/** Machine-readable explanations attached to engine output (§14). */
export const REASON = {
  INCOME_CONFIRMED: 'INCOME_CONFIRMED',
  INCOME_LATE: 'INCOME_LATE',
  HARD_CLAIM_ADDED: 'HARD_CLAIM_ADDED',
  RESERVATION_CONSUMED: 'RESERVATION_CONSUMED',
  GOAL_AT_RISK: 'GOAL_AT_RISK',
  FUNDING_GAP: 'FUNDING_GAP',
  DUPLICATE_HOLD: 'DUPLICATE_HOLD',
  REFUND_APPLIED: 'REFUND_APPLIED',
  BALANCE_ADJUSTED: 'BALANCE_ADJUSTED',
  BALANCE_STALE: 'BALANCE_STALE',
  OVERDUE_HARD_CLAIM: 'OVERDUE_HARD_CLAIM',
  CARD_SPEND_FUNDING_GAP: 'CARD_SPEND_FUNDING_GAP',
  PROTECTION_HORIZON_EXTENDED: 'PROTECTION_HORIZON_EXTENDED',
  BUFFER_SHORTFALL: 'BUFFER_SHORTFALL',
  FLEXIBLE_SHORTFALL: 'FLEXIBLE_SHORTFALL',
} as const;

export type ReasonCode = (typeof REASON)[keyof typeof REASON];
