// GENERATED by tools/generate_currencies.py — do not edit by hand.
// Edit tools/currencies.py and regenerate.


/// The currencies Upino offers, in the order the picker shows them.
///
/// [exponent] is how many decimal places the currency defines for its minor
/// unit. It is engine-critical: amounts are held as integer minor units, so
/// the wrong exponent means the wrong amount, not merely the wrong format.
library;

class CurrencyInfo {
  const CurrencyInfo({
    required this.code,
    required this.exponent,
    required this.symbol,
    required this.flagCountry,
    required this.country,
    required this.name,
  });

  final String code;
  final int exponent;
  final String symbol;

  /// ISO 3166-1 alpha-2, which the flag emoji is derived from.
  final String flagCountry;
  final String country;
  final String name;

  /// The two regional indicator letters Android draws as a flag.
  String get flag => String.fromCharCodes(
        flagCountry.codeUnits.map((c) => 0x1F1E6 + c - 0x41),
      );

  /// Matches a code, a country or a currency name, so "usd", "united" and
  /// "dollar" all find the US dollar.
  bool matches(String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return true;
    return code.toLowerCase().contains(q) ||
        country.toLowerCase().contains(q) ||
        name.toLowerCase().contains(q);
  }
}

const currencyCatalogue = <CurrencyInfo>[
  CurrencyInfo(code: 'USD', exponent: 2, symbol: '\$', flagCountry: 'US', country: 'United States', name: 'US dollar'),
  CurrencyInfo(code: 'EUR', exponent: 2, symbol: '€', flagCountry: 'EU', country: 'Eurozone', name: 'Euro'),
  CurrencyInfo(code: 'JPY', exponent: 0, symbol: '¥', flagCountry: 'JP', country: 'Japan', name: 'Japanese yen'),
  CurrencyInfo(code: 'GBP', exponent: 2, symbol: '£', flagCountry: 'GB', country: 'United Kingdom', name: 'Pound sterling'),
  CurrencyInfo(code: 'CNY', exponent: 2, symbol: '¥', flagCountry: 'CN', country: 'China', name: 'Chinese yuan'),
  CurrencyInfo(code: 'AUD', exponent: 2, symbol: '\$', flagCountry: 'AU', country: 'Australia', name: 'Australian dollar'),
  CurrencyInfo(code: 'CAD', exponent: 2, symbol: '\$', flagCountry: 'CA', country: 'Canada', name: 'Canadian dollar'),
  CurrencyInfo(code: 'CHF', exponent: 2, symbol: 'Fr', flagCountry: 'CH', country: 'Switzerland', name: 'Swiss franc'),
  CurrencyInfo(code: 'HKD', exponent: 2, symbol: '\$', flagCountry: 'HK', country: 'Hong Kong', name: 'Hong Kong dollar'),
  CurrencyInfo(code: 'SGD', exponent: 2, symbol: '\$', flagCountry: 'SG', country: 'Singapore', name: 'Singapore dollar'),
  CurrencyInfo(code: 'AED', exponent: 2, symbol: 'AED', flagCountry: 'AE', country: 'United Arab Emirates', name: 'UAE dirham'),
  CurrencyInfo(code: 'SAR', exponent: 2, symbol: 'SAR', flagCountry: 'SA', country: 'Saudi Arabia', name: 'Saudi riyal'),
  CurrencyInfo(code: 'IRR', exponent: 0, symbol: 'IRR', flagCountry: 'IR', country: 'Iran', name: 'Iranian rial'),
  CurrencyInfo(code: 'OMR', exponent: 3, symbol: 'OMR', flagCountry: 'OM', country: 'Oman', name: 'Omani rial'),
  CurrencyInfo(code: 'QAR', exponent: 2, symbol: 'QAR', flagCountry: 'QA', country: 'Qatar', name: 'Qatari riyal'),
  CurrencyInfo(code: 'KWD', exponent: 3, symbol: 'KWD', flagCountry: 'KW', country: 'Kuwait', name: 'Kuwaiti dinar'),
  CurrencyInfo(code: 'BHD', exponent: 3, symbol: 'BHD', flagCountry: 'BH', country: 'Bahrain', name: 'Bahraini dinar'),
  CurrencyInfo(code: 'INR', exponent: 2, symbol: '₹', flagCountry: 'IN', country: 'India', name: 'Indian rupee'),
  CurrencyInfo(code: 'KRW', exponent: 0, symbol: '₩', flagCountry: 'KR', country: 'South Korea', name: 'South Korean won'),
  CurrencyInfo(code: 'TRY', exponent: 2, symbol: '₺', flagCountry: 'TR', country: 'Türkiye', name: 'Turkish lira'),
  CurrencyInfo(code: 'RUB', exponent: 2, symbol: '₽', flagCountry: 'RU', country: 'Russia', name: 'Russian ruble'),
  CurrencyInfo(code: 'BRL', exponent: 2, symbol: 'R\$', flagCountry: 'BR', country: 'Brazil', name: 'Brazilian real'),
  CurrencyInfo(code: 'MXN', exponent: 2, symbol: '\$', flagCountry: 'MX', country: 'Mexico', name: 'Mexican peso'),
  CurrencyInfo(code: 'ZAR', exponent: 2, symbol: 'R', flagCountry: 'ZA', country: 'South Africa', name: 'South African rand'),
  CurrencyInfo(code: 'SEK', exponent: 2, symbol: 'kr', flagCountry: 'SE', country: 'Sweden', name: 'Swedish krona'),
  CurrencyInfo(code: 'NOK', exponent: 2, symbol: 'kr', flagCountry: 'NO', country: 'Norway', name: 'Norwegian krone'),
  CurrencyInfo(code: 'DKK', exponent: 2, symbol: 'kr', flagCountry: 'DK', country: 'Denmark', name: 'Danish krone'),
  CurrencyInfo(code: 'PLN', exponent: 2, symbol: 'zł', flagCountry: 'PL', country: 'Poland', name: 'Polish złoty'),
  CurrencyInfo(code: 'NZD', exponent: 2, symbol: '\$', flagCountry: 'NZ', country: 'New Zealand', name: 'New Zealand dollar'),
  CurrencyInfo(code: 'THB', exponent: 2, symbol: '฿', flagCountry: 'TH', country: 'Thailand', name: 'Thai baht'),
  CurrencyInfo(code: 'IDR', exponent: 2, symbol: 'Rp', flagCountry: 'ID', country: 'Indonesia', name: 'Indonesian rupiah'),
  CurrencyInfo(code: 'MYR', exponent: 2, symbol: 'RM', flagCountry: 'MY', country: 'Malaysia', name: 'Malaysian ringgit'),
  CurrencyInfo(code: 'PHP', exponent: 2, symbol: '₱', flagCountry: 'PH', country: 'Philippines', name: 'Philippine peso'),
  CurrencyInfo(code: 'TWD', exponent: 2, symbol: 'NT\$', flagCountry: 'TW', country: 'Taiwan', name: 'New Taiwan dollar'),
  CurrencyInfo(code: 'ILS', exponent: 2, symbol: '₪', flagCountry: 'IL', country: 'Israel', name: 'Israeli new shekel'),
  CurrencyInfo(code: 'CZK', exponent: 2, symbol: 'Kč', flagCountry: 'CZ', country: 'Czechia', name: 'Czech koruna'),
  CurrencyInfo(code: 'HUF', exponent: 2, symbol: 'Ft', flagCountry: 'HU', country: 'Hungary', name: 'Hungarian forint'),
  CurrencyInfo(code: 'RON', exponent: 2, symbol: 'lei', flagCountry: 'RO', country: 'Romania', name: 'Romanian leu'),
  CurrencyInfo(code: 'VND', exponent: 0, symbol: '₫', flagCountry: 'VN', country: 'Vietnam', name: 'Vietnamese dong'),
  CurrencyInfo(code: 'PKR', exponent: 2, symbol: 'PKR', flagCountry: 'PK', country: 'Pakistan', name: 'Pakistani rupee'),
  CurrencyInfo(code: 'BDT', exponent: 2, symbol: '৳', flagCountry: 'BD', country: 'Bangladesh', name: 'Bangladeshi taka'),
  CurrencyInfo(code: 'LKR', exponent: 2, symbol: 'LKR', flagCountry: 'LK', country: 'Sri Lanka', name: 'Sri Lankan rupee'),
  CurrencyInfo(code: 'NPR', exponent: 2, symbol: 'NPR', flagCountry: 'NP', country: 'Nepal', name: 'Nepalese rupee'),
  CurrencyInfo(code: 'AFN', exponent: 2, symbol: '؋', flagCountry: 'AF', country: 'Afghanistan', name: 'Afghan afghani'),
  CurrencyInfo(code: 'MMK', exponent: 2, symbol: 'K', flagCountry: 'MM', country: 'Myanmar', name: 'Burmese kyat'),
  CurrencyInfo(code: 'KHR', exponent: 2, symbol: '៛', flagCountry: 'KH', country: 'Cambodia', name: 'Cambodian riel'),
  CurrencyInfo(code: 'LAK', exponent: 2, symbol: '₭', flagCountry: 'LA', country: 'Laos', name: 'Lao kip'),
  CurrencyInfo(code: 'BND', exponent: 2, symbol: '\$', flagCountry: 'BN', country: 'Brunei', name: 'Brunei dollar'),
  CurrencyInfo(code: 'MOP', exponent: 2, symbol: 'MOP', flagCountry: 'MO', country: 'Macau', name: 'Macanese pataca'),
  CurrencyInfo(code: 'MNT', exponent: 2, symbol: '₮', flagCountry: 'MN', country: 'Mongolia', name: 'Mongolian tugrik'),
  CurrencyInfo(code: 'MVR', exponent: 2, symbol: 'MVR', flagCountry: 'MV', country: 'Maldives', name: 'Maldivian rufiyaa'),
  CurrencyInfo(code: 'BTN', exponent: 2, symbol: 'BTN', flagCountry: 'BT', country: 'Bhutan', name: 'Bhutanese ngultrum'),
  CurrencyInfo(code: 'KZT', exponent: 2, symbol: '₸', flagCountry: 'KZ', country: 'Kazakhstan', name: 'Kazakhstani tenge'),
  CurrencyInfo(code: 'UZS', exponent: 2, symbol: 'UZS', flagCountry: 'UZ', country: 'Uzbekistan', name: 'Uzbekistani som'),
  CurrencyInfo(code: 'AZN', exponent: 2, symbol: '₼', flagCountry: 'AZ', country: 'Azerbaijan', name: 'Azerbaijani manat'),
  CurrencyInfo(code: 'GEL', exponent: 2, symbol: '₾', flagCountry: 'GE', country: 'Georgia', name: 'Georgian lari'),
  CurrencyInfo(code: 'AMD', exponent: 2, symbol: '֏', flagCountry: 'AM', country: 'Armenia', name: 'Armenian dram'),
  CurrencyInfo(code: 'TJS', exponent: 2, symbol: 'TJS', flagCountry: 'TJ', country: 'Tajikistan', name: 'Tajikistani somoni'),
  CurrencyInfo(code: 'TMT', exponent: 2, symbol: 'TMT', flagCountry: 'TM', country: 'Turkmenistan', name: 'Turkmenistan manat'),
  CurrencyInfo(code: 'KGS', exponent: 2, symbol: 'KGS', flagCountry: 'KG', country: 'Kyrgyzstan', name: 'Kyrgyzstani som'),
  CurrencyInfo(code: 'IQD', exponent: 3, symbol: 'IQD', flagCountry: 'IQ', country: 'Iraq', name: 'Iraqi dinar'),
  CurrencyInfo(code: 'JOD', exponent: 3, symbol: 'JOD', flagCountry: 'JO', country: 'Jordan', name: 'Jordanian dinar'),
  CurrencyInfo(code: 'LBP', exponent: 2, symbol: 'LBP', flagCountry: 'LB', country: 'Lebanon', name: 'Lebanese pound'),
  CurrencyInfo(code: 'SYP', exponent: 2, symbol: 'SYP', flagCountry: 'SY', country: 'Syria', name: 'Syrian pound'),
  CurrencyInfo(code: 'YER', exponent: 2, symbol: 'YER', flagCountry: 'YE', country: 'Yemen', name: 'Yemeni rial'),
  CurrencyInfo(code: 'EGP', exponent: 2, symbol: 'EGP', flagCountry: 'EG', country: 'Egypt', name: 'Egyptian pound'),
  CurrencyInfo(code: 'MAD', exponent: 2, symbol: 'MAD', flagCountry: 'MA', country: 'Morocco', name: 'Moroccan dirham'),
  CurrencyInfo(code: 'DZD', exponent: 2, symbol: 'DZD', flagCountry: 'DZ', country: 'Algeria', name: 'Algerian dinar'),
  CurrencyInfo(code: 'TND', exponent: 3, symbol: 'TND', flagCountry: 'TN', country: 'Tunisia', name: 'Tunisian dinar'),
  CurrencyInfo(code: 'LYD', exponent: 3, symbol: 'LYD', flagCountry: 'LY', country: 'Libya', name: 'Libyan dinar'),
  CurrencyInfo(code: 'ISK', exponent: 0, symbol: 'kr', flagCountry: 'IS', country: 'Iceland', name: 'Icelandic króna'),
  CurrencyInfo(code: 'BGN', exponent: 2, symbol: 'лв', flagCountry: 'BG', country: 'Bulgaria', name: 'Bulgarian lev'),
  CurrencyInfo(code: 'RSD', exponent: 2, symbol: 'RSD', flagCountry: 'RS', country: 'Serbia', name: 'Serbian dinar'),
  CurrencyInfo(code: 'UAH', exponent: 2, symbol: '₴', flagCountry: 'UA', country: 'Ukraine', name: 'Ukrainian hryvnia'),
  CurrencyInfo(code: 'BYN', exponent: 2, symbol: 'Br', flagCountry: 'BY', country: 'Belarus', name: 'Belarusian ruble'),
  CurrencyInfo(code: 'MDL', exponent: 2, symbol: 'MDL', flagCountry: 'MD', country: 'Moldova', name: 'Moldovan leu'),
  CurrencyInfo(code: 'ALL', exponent: 2, symbol: 'L', flagCountry: 'AL', country: 'Albania', name: 'Albanian lek'),
  CurrencyInfo(code: 'MKD', exponent: 2, symbol: 'MKD', flagCountry: 'MK', country: 'North Macedonia', name: 'Macedonian denar'),
  CurrencyInfo(code: 'BAM', exponent: 2, symbol: 'KM', flagCountry: 'BA', country: 'Bosnia and Herzegovina', name: 'Convertible mark'),
  CurrencyInfo(code: 'GIP', exponent: 2, symbol: '£', flagCountry: 'GI', country: 'Gibraltar', name: 'Gibraltar pound'),
  CurrencyInfo(code: 'ARS', exponent: 2, symbol: '\$', flagCountry: 'AR', country: 'Argentina', name: 'Argentine peso'),
  CurrencyInfo(code: 'CLP', exponent: 0, symbol: '\$', flagCountry: 'CL', country: 'Chile', name: 'Chilean peso'),
  CurrencyInfo(code: 'COP', exponent: 2, symbol: '\$', flagCountry: 'CO', country: 'Colombia', name: 'Colombian peso'),
  CurrencyInfo(code: 'PEN', exponent: 2, symbol: 'S/', flagCountry: 'PE', country: 'Peru', name: 'Peruvian sol'),
  CurrencyInfo(code: 'UYU', exponent: 2, symbol: '\$', flagCountry: 'UY', country: 'Uruguay', name: 'Uruguayan peso'),
  CurrencyInfo(code: 'PYG', exponent: 0, symbol: '₲', flagCountry: 'PY', country: 'Paraguay', name: 'Paraguayan guarani'),
  CurrencyInfo(code: 'BOB', exponent: 2, symbol: 'Bs', flagCountry: 'BO', country: 'Bolivia', name: 'Bolivian boliviano'),
  CurrencyInfo(code: 'VES', exponent: 2, symbol: 'Bs', flagCountry: 'VE', country: 'Venezuela', name: 'Venezuelan bolívar'),
  CurrencyInfo(code: 'GTQ', exponent: 2, symbol: 'Q', flagCountry: 'GT', country: 'Guatemala', name: 'Guatemalan quetzal'),
  CurrencyInfo(code: 'HNL', exponent: 2, symbol: 'L', flagCountry: 'HN', country: 'Honduras', name: 'Honduran lempira'),
  CurrencyInfo(code: 'NIO', exponent: 2, symbol: 'C\$', flagCountry: 'NI', country: 'Nicaragua', name: 'Nicaraguan córdoba'),
  CurrencyInfo(code: 'CRC', exponent: 2, symbol: '₡', flagCountry: 'CR', country: 'Costa Rica', name: 'Costa Rican colón'),
  CurrencyInfo(code: 'PAB', exponent: 2, symbol: 'B/', flagCountry: 'PA', country: 'Panama', name: 'Panamanian balboa'),
  CurrencyInfo(code: 'DOP', exponent: 2, symbol: 'RD\$', flagCountry: 'DO', country: 'Dominican Republic', name: 'Dominican peso'),
  CurrencyInfo(code: 'CUP', exponent: 2, symbol: '\$', flagCountry: 'CU', country: 'Cuba', name: 'Cuban peso'),
  CurrencyInfo(code: 'JMD', exponent: 2, symbol: '\$', flagCountry: 'JM', country: 'Jamaica', name: 'Jamaican dollar'),
  CurrencyInfo(code: 'TTD', exponent: 2, symbol: '\$', flagCountry: 'TT', country: 'Trinidad and Tobago', name: 'Trinidad and Tobago dollar'),
  CurrencyInfo(code: 'BBD', exponent: 2, symbol: '\$', flagCountry: 'BB', country: 'Barbados', name: 'Barbadian dollar'),
  CurrencyInfo(code: 'BSD', exponent: 2, symbol: '\$', flagCountry: 'BS', country: 'Bahamas', name: 'Bahamian dollar'),
  CurrencyInfo(code: 'BZD', exponent: 2, symbol: '\$', flagCountry: 'BZ', country: 'Belize', name: 'Belize dollar'),
  CurrencyInfo(code: 'XCD', exponent: 2, symbol: '\$', flagCountry: 'AG', country: 'Eastern Caribbean', name: 'East Caribbean dollar'),
  CurrencyInfo(code: 'HTG', exponent: 2, symbol: 'G', flagCountry: 'HT', country: 'Haiti', name: 'Haitian gourde'),
  CurrencyInfo(code: 'SRD', exponent: 2, symbol: '\$', flagCountry: 'SR', country: 'Suriname', name: 'Surinamese dollar'),
  CurrencyInfo(code: 'GYD', exponent: 2, symbol: '\$', flagCountry: 'GY', country: 'Guyana', name: 'Guyanese dollar'),
  CurrencyInfo(code: 'ANG', exponent: 2, symbol: 'ƒ', flagCountry: 'CW', country: 'Curaçao', name: 'Netherlands Antillean guilder'),
  CurrencyInfo(code: 'AWG', exponent: 2, symbol: 'ƒ', flagCountry: 'AW', country: 'Aruba', name: 'Aruban florin'),
  CurrencyInfo(code: 'KYD', exponent: 2, symbol: '\$', flagCountry: 'KY', country: 'Cayman Islands', name: 'Cayman Islands dollar'),
  CurrencyInfo(code: 'BMD', exponent: 2, symbol: '\$', flagCountry: 'BM', country: 'Bermuda', name: 'Bermudian dollar'),
  CurrencyInfo(code: 'NGN', exponent: 2, symbol: '₦', flagCountry: 'NG', country: 'Nigeria', name: 'Nigerian naira'),
  CurrencyInfo(code: 'GHS', exponent: 2, symbol: '₵', flagCountry: 'GH', country: 'Ghana', name: 'Ghanaian cedi'),
  CurrencyInfo(code: 'KES', exponent: 2, symbol: 'KSh', flagCountry: 'KE', country: 'Kenya', name: 'Kenyan shilling'),
  CurrencyInfo(code: 'TZS', exponent: 2, symbol: 'TSh', flagCountry: 'TZ', country: 'Tanzania', name: 'Tanzanian shilling'),
  CurrencyInfo(code: 'UGX', exponent: 0, symbol: 'USh', flagCountry: 'UG', country: 'Uganda', name: 'Ugandan shilling'),
  CurrencyInfo(code: 'ETB', exponent: 2, symbol: 'ETB', flagCountry: 'ET', country: 'Ethiopia', name: 'Ethiopian birr'),
  CurrencyInfo(code: 'SDG', exponent: 2, symbol: 'SDG', flagCountry: 'SD', country: 'Sudan', name: 'Sudanese pound'),
  CurrencyInfo(code: 'SSP', exponent: 2, symbol: 'SSP', flagCountry: 'SS', country: 'South Sudan', name: 'South Sudanese pound'),
  CurrencyInfo(code: 'SOS', exponent: 2, symbol: 'SOS', flagCountry: 'SO', country: 'Somalia', name: 'Somali shilling'),
  CurrencyInfo(code: 'ERN', exponent: 2, symbol: 'ERN', flagCountry: 'ER', country: 'Eritrea', name: 'Eritrean nakfa'),
  CurrencyInfo(code: 'DJF', exponent: 0, symbol: 'DJF', flagCountry: 'DJ', country: 'Djibouti', name: 'Djiboutian franc'),
  CurrencyInfo(code: 'RWF', exponent: 0, symbol: 'RWF', flagCountry: 'RW', country: 'Rwanda', name: 'Rwandan franc'),
  CurrencyInfo(code: 'BIF', exponent: 0, symbol: 'BIF', flagCountry: 'BI', country: 'Burundi', name: 'Burundian franc'),
  CurrencyInfo(code: 'XOF', exponent: 0, symbol: 'XOF', flagCountry: 'SN', country: 'West Africa', name: 'West African CFA franc'),
  CurrencyInfo(code: 'XAF', exponent: 0, symbol: 'XAF', flagCountry: 'CM', country: 'Central Africa', name: 'Central African CFA franc'),
  CurrencyInfo(code: 'ZMW', exponent: 2, symbol: 'ZK', flagCountry: 'ZM', country: 'Zambia', name: 'Zambian kwacha'),
  CurrencyInfo(code: 'MWK', exponent: 2, symbol: 'MK', flagCountry: 'MW', country: 'Malawi', name: 'Malawian kwacha'),
  CurrencyInfo(code: 'MZN', exponent: 2, symbol: 'MT', flagCountry: 'MZ', country: 'Mozambique', name: 'Mozambican metical'),
  CurrencyInfo(code: 'AOA', exponent: 2, symbol: 'Kz', flagCountry: 'AO', country: 'Angola', name: 'Angolan kwanza'),
  CurrencyInfo(code: 'BWP', exponent: 2, symbol: 'P', flagCountry: 'BW', country: 'Botswana', name: 'Botswana pula'),
  CurrencyInfo(code: 'NAD', exponent: 2, symbol: '\$', flagCountry: 'NA', country: 'Namibia', name: 'Namibian dollar'),
  CurrencyInfo(code: 'SZL', exponent: 2, symbol: 'E', flagCountry: 'SZ', country: 'Eswatini', name: 'Swazi lilangeni'),
  CurrencyInfo(code: 'LSL', exponent: 2, symbol: 'L', flagCountry: 'LS', country: 'Lesotho', name: 'Lesotho loti'),
  CurrencyInfo(code: 'MUR', exponent: 2, symbol: 'MUR', flagCountry: 'MU', country: 'Mauritius', name: 'Mauritian rupee'),
  CurrencyInfo(code: 'SCR', exponent: 2, symbol: 'SCR', flagCountry: 'SC', country: 'Seychelles', name: 'Seychellois rupee'),
  CurrencyInfo(code: 'MGA', exponent: 2, symbol: 'MGA', flagCountry: 'MG', country: 'Madagascar', name: 'Malagasy ariary'),
  CurrencyInfo(code: 'KMF', exponent: 0, symbol: 'KMF', flagCountry: 'KM', country: 'Comoros', name: 'Comorian franc'),
  CurrencyInfo(code: 'CVE', exponent: 2, symbol: 'CVE', flagCountry: 'CV', country: 'Cabo Verde', name: 'Cape Verdean escudo'),
  CurrencyInfo(code: 'STN', exponent: 2, symbol: 'STN', flagCountry: 'ST', country: 'São Tomé and Príncipe', name: 'São Tomé and Príncipe dobra'),
  CurrencyInfo(code: 'GMD', exponent: 2, symbol: 'GMD', flagCountry: 'GM', country: 'Gambia', name: 'Gambian dalasi'),
  CurrencyInfo(code: 'GNF', exponent: 0, symbol: 'GNF', flagCountry: 'GN', country: 'Guinea', name: 'Guinean franc'),
  CurrencyInfo(code: 'SLE', exponent: 2, symbol: 'SLE', flagCountry: 'SL', country: 'Sierra Leone', name: 'Sierra Leonean leone'),
  CurrencyInfo(code: 'LRD', exponent: 2, symbol: '\$', flagCountry: 'LR', country: 'Liberia', name: 'Liberian dollar'),
  CurrencyInfo(code: 'MRU', exponent: 2, symbol: 'MRU', flagCountry: 'MR', country: 'Mauritania', name: 'Mauritanian ouguiya'),
  CurrencyInfo(code: 'FJD', exponent: 2, symbol: '\$', flagCountry: 'FJ', country: 'Fiji', name: 'Fijian dollar'),
  CurrencyInfo(code: 'PGK', exponent: 2, symbol: 'K', flagCountry: 'PG', country: 'Papua New Guinea', name: 'Papua New Guinean kina'),
  CurrencyInfo(code: 'SBD', exponent: 2, symbol: '\$', flagCountry: 'SB', country: 'Solomon Islands', name: 'Solomon Islands dollar'),
  CurrencyInfo(code: 'WST', exponent: 2, symbol: 'WST', flagCountry: 'WS', country: 'Samoa', name: 'Samoan tala'),
  CurrencyInfo(code: 'TOP', exponent: 2, symbol: 'TOP', flagCountry: 'TO', country: 'Tonga', name: 'Tongan paʻanga'),
  CurrencyInfo(code: 'VUV', exponent: 0, symbol: 'VUV', flagCountry: 'VU', country: 'Vanuatu', name: 'Vanuatu vatu'),
  CurrencyInfo(code: 'XPF', exponent: 0, symbol: 'XPF', flagCountry: 'PF', country: 'French Pacific', name: 'CFP franc'),
];
