#!/usr/bin/env python3
"""Emit the app's icons from Iconify's published sets.

    npm pack @iconify-json/{solar,ph,mingcute,hugeicons,lucide,circle-flags}
    python3 tools/generate_icons.py <dir-with-the-unpacked-packages>

Each interface icon names the family it comes from. The set started as
lucide alone, on the argument that one family is what makes a set look
considered; in practice it read as flat, and the icons were chosen one by
one from the picker instead — mostly Solar's linear weight, which is
rounder and lighter, with a few from Mingcute and Hugeicons where Solar
had nothing better. They still share a 24px grid and a ~1.5px stroke,
which is the part that actually holds a set together.

circle-flags gives the round country flags, so the currency list reads as
a list rather than as a column of little rectangles.

The bodies are emitted as Dart string constants rather than asset files. An
icon is a handful of path data; making 150 of them assets means 150 async
loads and a pubspec that has to list every one.

Run it again to change the set or add an icon. Do not edit the output.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# What the interface uses, and what it is for. The name on the left is the
# one the app says; the right is 'family:icon' as Iconify publishes it.
UI_ICONS = {
    'home': 'solar:home-angle-linear',
    'plan': 'solar:wallet-2-linear',
    'goals': 'solar:target-linear',
    'activity': 'solar:bill-list-linear',
    'profile': 'solar:user-linear',
    'search': 'solar:magnifer-line-duotone',
    'check': 'lucide:check',
    'chevronRight': 'mingcute:right-line',
    'chevronUp': 'solar:alt-arrow-up-linear',
    'chevronDown': 'solar:alt-arrow-down-linear',
    'swap': 'mingcute:transfer-line',
    'add': 'solar:add-square-linear',
    'tune': 'hugeicons:filter-horizontal',
    'trendingUp': 'solar:graph-up-linear',
    'close': 'solar:close-square-linear',
    'confirmed': 'solar:check-circle-linear',
    'alert': 'solar:danger-linear',
    'more': 'mingcute:more-1-line',
    'ask': 'solar:question-square-linear',
    'camera': 'solar:camera-minimalistic-linear',
    'mic': 'solar:microphone-3-linear',
    'bell': 'solar:bell-linear',
    'chat': 'solar:chat-round-line-linear',
    'gallery': 'solar:gallery-minimalistic-linear',
    'back': 'mingcute:left-line',
    'receipt': 'solar:document-text-linear',
    'radioOff': 'solar:circle-dashed-linear',
    'radioOn': 'hugeicons:circle-dot',
}

# Every family an icon above is taken from.
UI_FAMILIES = sorted({ref.split(':', 1)[0] for ref in UI_ICONS.values()})


def dart_string(s):
    return "'" + s.replace('\\', r'\\').replace("'", r"\'").replace('$', r'\$') + "'"


def load(pkg_dir, name):
    path = os.path.join(pkg_dir, name, 'icons.json')
    with open(path) as f:
        return json.load(f)


def wrap(body, width, height):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'viewBox="0 0 {width} {height}">{body}</svg>')


def main(pkg_dir):
    def package(prefix):
        hit = [d for d in sorted(os.listdir(pkg_dir))
               if d.startswith(f'iconify-json-{prefix}-')]
        assert hit, f'no unpacked @iconify-json/{prefix} in {pkg_dir}'
        return load(pkg_dir, hit[0])

    families = {name: package(name) for name in UI_FAMILIES}
    flags = package('circle-flags')

    sys.path.insert(0, HERE)
    from currencies import TABLE
    needed = sorted({row[3].lower() for row in TABLE})

    missing = [ref for ref in UI_ICONS.values()
               if ref.split(':', 1)[1] not in
               families[ref.split(':', 1)[0]]['icons']]
    assert not missing, f'not published: {missing}'
    absent = [c for c in needed if c not in flags['icons']]
    assert not absent, f'no circle flag for: {absent}'

    out = ['// GENERATED by tools/generate_icons.py — do not edit by hand.',
           '// ' + ', '.join(f'{n} {families[n].get("lastModified")}'
                             for n in UI_FAMILIES)
           + f", circle-flags {flags.get('lastModified')}.",
           '',
           '/// The app\'s icons, as SVG source.',
           '///',
           '/// Interface icons are picked one by one, mostly from Solar\'s',
           '/// linear weight, on a 24px grid. They carry `currentColor`, so',
           '/// [UpinoIcon] tints them the way an icon font would.',
           '///',
           '/// Flags come from circle-flags and are full colour, so nothing',
           '/// tints them.',
           'library;',
           '',
           'const upinoIcons = <String, String>{']
    for name, ref in UI_ICONS.items():
        prefix, src = ref.split(':', 1)
        family = families[prefix]
        icon = family['icons'][src]
        body = wrap(icon['body'],
                    icon.get('width', family.get('width', 24)),
                    icon.get('height', family.get('height', 24)))
        out.append(f'  {dart_string(name)}: {dart_string(body)},  // {ref}')
    out.append('};')
    out.append('')
    out.append('/// Keyed by ISO 3166-1 alpha-2, lowercased.')
    out.append('const countryFlags = <String, String>{')
    fw, fh = flags.get('width', 512), flags.get('height', 512)
    for code in needed:
        icon = flags['icons'][code]
        body = wrap(icon['body'], icon.get('width', fw), icon.get('height', fh))
        out.append(f'  {dart_string(code)}: {dart_string(body)},')
    out.append('};')
    out.append('')

    path = os.path.join(ROOT, 'app', 'lib', 'design', 'icons.dart')
    with open(path, 'w') as f:
        f.write('\n'.join(out))
    print('wrote', path)
    print(len(UI_ICONS), 'interface icons from',
          ', '.join(UI_FAMILIES) + ',', len(needed), 'flags')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else '/tmp/iconify')
