#!/usr/bin/env python3
"""Emit the app's icons from Iconify's published sets.

    npm pack @iconify-json/lucide @iconify-json/circle-flags
    python3 tools/generate_icons.py <dir-with-the-unpacked-packages>

Two sets, for two different jobs:

  lucide        the interface icons — one weight, one stroke, drawn on the
                same 24px grid, which is what makes a set look considered
                rather than assembled.
  circle-flags  round country flags, so the currency list reads as a list
                rather than as a column of little rectangles.

The bodies are emitted as Dart string constants rather than asset files. An
icon is a handful of path data; making 150 of them assets means 150 async
loads and a pubspec that has to list every one.

Run it again to change the set or add an icon. Do not edit the output.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# What the interface uses, and what it is for. The name on the left is the
# one the app says; the right is lucide's.
UI_ICONS = {
    'home': 'house',
    'plan': 'wallet',
    'goals': 'target',
    'activity': 'receipt-text',
    'profile': 'circle-user-round',
    'search': 'search',
    'check': 'check',
    'chevronRight': 'chevron-right',
    'chevronUp': 'chevron-up',
    'chevronDown': 'chevron-down',
    'swap': 'arrow-left-right',
    'add': 'plus',
    'tune': 'sliders-horizontal',
    'trendingUp': 'trending-up',
    'close': 'x',
    'confirmed': 'circle-check',
    'alert': 'circle-alert',
    'more': 'ellipsis',
    'ask': 'circle-question-mark',
    'camera': 'camera',
    'gallery': 'image',
    'back': 'arrow-left',
    'receipt': 'receipt-text',
    'radioOff': 'circle',
    'radioOn': 'circle-dot',
}


def dart_string(s):
    return "'" + s.replace('\\', r'\\').replace("'", r"\'").replace('$', r'\$') + "'"


def load(pkg_dir, name):
    path = os.path.join(pkg_dir, name, 'icons.json')
    with open(path) as f:
        return json.load(f)


def wrap(body, width, height):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'viewBox="0 0 {width} {height}">{body}</svg>')


def main(pkg_dir):
    lucide = load(pkg_dir, [d for d in os.listdir(pkg_dir)
                            if d.startswith('iconify-json-lucide')][0])
    flags = load(pkg_dir, [d for d in os.listdir(pkg_dir)
                           if d.startswith('iconify-json-circle-flags')][0])

    sys.path.insert(0, HERE)
    from currencies import TABLE
    needed = sorted({row[3].lower() for row in TABLE})

    missing = [n for n in UI_ICONS.values() if n not in lucide['icons']]
    assert not missing, f'not in lucide: {missing}'
    absent = [c for c in needed if c not in flags['icons']]
    assert not absent, f'no circle flag for: {absent}'

    out = ['// GENERATED by tools/generate_icons.py — do not edit by hand.',
           f"// lucide {lucide.get('lastModified')}, "
           f"circle-flags {flags.get('lastModified')}.",
           '',
           '/// The app\'s icons, as SVG source.',
           '///',
           '/// Interface icons come from lucide: one weight, one stroke, one',
           '/// 24px grid. They carry `currentColor`, so [UpinoIcon] tints them',
           '/// the same way an icon font would.',
           '///',
           '/// Flags come from circle-flags and are full colour, so nothing',
           '/// tints them.',
           'library;',
           '',
           'const upinoIcons = <String, String>{']
    lw, lh = lucide.get('width', 24), lucide.get('height', 24)
    for name, src in UI_ICONS.items():
        icon = lucide['icons'][src]
        body = wrap(icon['body'], icon.get('width', lw), icon.get('height', lh))
        out.append(f'  {dart_string(name)}: {dart_string(body)},')
    out.append('};')
    out.append('')
    out.append('/// Keyed by ISO 3166-1 alpha-2, lowercased.')
    out.append('const countryFlags = <String, String>{')
    fw, fh = flags.get('width', 512), flags.get('height', 512)
    for code in needed:
        icon = flags['icons'][code]
        body = wrap(icon['body'], icon.get('width', fw), icon.get('height', fh))
        out.append(f'  {dart_string(code)}: {dart_string(body)},')
    out.append('};')
    out.append('')

    path = os.path.join(ROOT, 'app', 'lib', 'design', 'icons.dart')
    with open(path, 'w') as f:
        f.write('\n'.join(out))
    print('wrote', path)
    print(len(UI_ICONS), 'interface icons,', len(needed), 'flags')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else '/tmp/iconify')
