#!/usr/bin/env python3
"""Emit the currency table for both engines from tools/currencies.py.

Two implementations share one fixture table, so they must not disagree about
how many decimal places a currency has — a mismatch there would let the same
input mean different amounts on each side. Generating both files from one
source is cheaper than a test that checks they still match.

    python3 tools/generate_currencies.py

Regenerate and commit the output whenever the table changes.
"""
import os
import sys
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from currencies import TABLE, ZERO_DECIMAL, THREE_DECIMAL, EXCEPTIONS  # noqa: E402

BANNER = ('// GENERATED by tools/generate_currencies.py — do not edit by hand.\n'
          '// Edit tools/currencies.py and regenerate.\n')


def check():
    codes = [r[0] for r in TABLE]
    assert len(codes) == len(set(codes)), 'duplicate currency code'
    assert len(codes) >= 100, f'only {len(codes)} currencies'
    for code, exp, symbol, flag, country, name in TABLE:
        want = EXCEPTIONS.get(
            code, 0 if code in ZERO_DECIMAL else 3 if code in THREE_DECIMAL else 2)
        assert exp == want, f'{code} exponent {exp}, expected {want}'
        assert len(code) == 3 and code.isupper(), code
        assert len(flag) == 2 and flag.isupper(), f'{code} flag {flag}'
        assert symbol and country and name, code
    missing = (ZERO_DECIMAL | THREE_DECIMAL) - set(codes)
    assert not missing, f'special-exponent codes absent: {sorted(missing)}'


def fold(s):
    """Lowercase and strip accents: 'São Tomé' becomes 'sao tome'.

    Characters with no ASCII equivalent, such as the Tongan okina, are
    dropped rather than kept, since nobody types them into a search box.
    """
    decomposed = unicodedata.normalize('NFKD', s.lower())
    stripped = ''.join(c for c in decomposed if not unicodedata.combining(c))
    # A handful do not decompose: ł, ø, đ.
    for a, b in [('\u0142', 'l'), ('\u00f8', 'o'), ('\u0111', 'd'),
                 ('\u00e6', 'ae'), ('\u00df', 'ss')]:
        stripped = stripped.replace(a, b)
    return ''.join(c for c in stripped if ord(c) < 128)


def dart_string(s):
    return "'" + s.replace('\\', r'\\').replace("'", r"\'").replace('$', r'\$') + "'"


def ts_string(s):
    return "'" + s.replace('\\', r'\\').replace("'", r"\'") + "'"


def write_dart():
    out = [BANNER, '''
/// The currencies Upino offers, in the order the picker shows them.
///
/// [exponent] is how many decimal places the currency defines for its minor
/// unit. It is engine-critical: amounts are held as integer minor units, so
/// the wrong exponent means the wrong amount, not merely the wrong format.
library;

class CurrencyInfo {
  const CurrencyInfo({
    required this.code,
    required this.exponent,
    required this.symbol,
    required this.flagCountry,
    required this.country,
    required this.name,
    required this.searchKey,
  });

  final String code;
  final int exponent;
  final String symbol;

  /// ISO 3166-1 alpha-2, which the flag emoji is derived from.
  final String flagCountry;
  final String country;
  final String name;

  /// The code, country and name folded to lowercase ASCII, so that someone
  /// typing "turkiye", "sao tome" or "zloty" without the accent still finds
  /// the row. Generated, because folding correctly needs a Unicode table.
  final String searchKey;

  /// The two regional indicator letters Android draws as a flag.
  String get flag => String.fromCharCodes(
        flagCountry.codeUnits.map((c) => 0x1F1E6 + c - 0x41),
      );

  /// The three ways in: the country, what the money is called, and the
  /// three-letter code. "united", "dollar" and "usd" all find the US dollar.
  ///
  /// [searchKey] holds all three folded to plain ASCII; the raw fields are
  /// checked too so that typing the accent works as well as leaving it off.
  bool matches(String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return true;
    return searchKey.contains(q) ||
        country.toLowerCase().contains(q) ||
        name.toLowerCase().contains(q);
  }
}

const currencyCatalogue = <CurrencyInfo>[''']
    for code, exp, symbol, flag, country, name in TABLE:
        out.append(
            '  CurrencyInfo(code: %s, exponent: %d, symbol: %s, '
            'flagCountry: %s, country: %s, name: %s, searchKey: %s),' % (
                dart_string(code), exp, dart_string(symbol),
                dart_string(flag), dart_string(country), dart_string(name),
                dart_string(fold(' '.join([code, country, name])))))
    out.append('];\n')
    path = os.path.join(ROOT, 'app', 'lib', 'engine', 'currencies.dart')
    with open(path, 'w') as f:
        f.write('\n'.join(out))
    return path


def write_ts():
    out = [BANNER, '''
/**
 * The currencies Upino offers. `exponent` is the number of decimal places the
 * currency defines for its minor unit, per ISO 4217. Authoritative amounts are
 * held as integer minor units (§5, §5.1), so this is engine-critical data: the
 * wrong exponent means the wrong amount, not merely the wrong format.
 */
export const CURRENCY_TABLE: ReadonlyArray<readonly [string, number]> = [''']
    for code, exp, *_ in TABLE:
        out.append('  [%s, %d],' % (ts_string(code), exp))
    out.append('];\n')
    path = os.path.join(ROOT, 'src', 'money', 'currency-table.ts')
    with open(path, 'w') as f:
        f.write('\n'.join(out))
    return path


if __name__ == '__main__':
    check()
    print('wrote', write_dart())
    print('wrote', write_ts())
    print(len(TABLE), 'currencies')
